spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/create-learn-db?useSSL=true&serverTimezone=UTC
    username: prod_user
    password: ${DB_PASSWORD}   # recommend from environment variable

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    org.hibernate.SQL: info

minio:
  url: https://minio.prod.company.com
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
