spring:
  datasource:
    url: jdbc:mysql://localhost:3306/create-learn-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: developer
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123

app:
  init-mock: true
