spring:
  datasource:
    url: jdbc:mysql://mysql:3306/create-learn-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: developer
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: info
    org.project.createlearnbe: info
  file:
    name: /app/logs/app.log

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket: create-learn-storage

app:
  init-mock: false
  top-class-limit: 7

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
